####################################################################
# Docker compose file for all the servers needed for home-assistant
# This compose file consists of the following server applications:
# - Home-Assistant (external: localhost:8123)
# - Mqtt (external: localhost:8883 internal: mqtt:1883)
# - Settings Container (used to do initial HA settings copy)
#
# https://docs.docker.com/compose/
# https://docs.docker.com/compose/compose-file/compose-file-v2/
####################################################################

version: "2"
services:
  ############################################################
  # Home-assistant server (8123 public port)
  # https://hub.docker.com/r/homeassistant/home-assistant/
  ############################################################
  home-assistant:
    container_name: homeassistant_ha
    image: "homeassistant/raspberrypi3-homeassistant:stable"
    depends_on:
      # Start settings container first
      - ha_settings
      # Start mqtt first
      - mqtt
    links:
      # Link ports from mqtt container 
      - mqtt
    restart: always
    volumes:
      # Home-assistant config directory
      - homeassistant:/config
      # Timezone configuration (Linux only)
      - /etc/localtime:/etc/localtime:ro
    ports:
      # Expose home-assistant port on host interface
      - 8123:8123
    env_file:
      # Read all environment variables from the env file
      - ./home-assistant/ha.env

  ############################################################
  # MQTT Server (8883 public port)
  # https://hub.docker.com/_/eclipse-mosquitto/
  ############################################################
  mqtt:
    container_name: homeassistant_mqtt
    image: eclipse-mosquitto:latest
    ports:
      # Expose public TLS port 
      - 8883:8883
      # Internal port
      - 1883
    volumes:
      # The mosquitto configuration file
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # The authorization file
      - ./mosquitto/passwd:/mosquitto/config/passwd
      # Certificates
      - ./mosquitto/cert:/mosquitto/config/cert
      # Log directory
      # - ./mosquitto/log:/mosquitto/log
      # The data dir for persistance
      - mosquito:/mosquitto/data
      # Timezone configuration (Linux only)
      - /etc/localtime:/etc/localtime:ro
    restart: always

  ##############################################################
  # Settings container
  # Used to copy initial Home Assistant settings
  ##############################################################
  ha_settings:
    container_name: homeassistant_settings
    build: 
      context: settings-container
    volumes:
      - homeassistant:/config/
      - ./home-assistant:/home-assistant/
    environment: 
      - FORCE_RESET_CONFIG=TRUE
volumes:
  homeassistant: {}
  mosquito: {}